CREATE TABLE smp_payment_transactions
(
    id                    VARCHAR(255)                NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by            VARCHAR(255),
    updated_by            VARCHAR(255),
    transaction_id        VARCHAR(255),
    subscription_id       VARCHAR(255)                NOT NULL,
    amount                DECIMAL                     NOT NULL,
    currency              VARCHAR(255)                NOT NULL,
    payment_method        SMALLINT                    NOT NULL,
    provider              VARCHAR(255)                NOT NULL,
    transaction_reference VARCHAR(255)                NOT NULL,
    provider_reference    VARCHAR(255),
    status                VARCHAR(255),
    CONSTRAINT pk_smp_payment_transactions PRIMARY KEY (id)
);

CREATE TABLE smp_registered_services
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by       VARCHAR(255),
    updated_by       VARCHAR(255),
    service_id       VARCHAR(255),
    name             VARCHAR(255)                            NOT NULL,
    description      VARCHAR(255),
    api_key          VARCHAR(255)                            NOT NULL,
    api_secret_hash  VARCHAR(255)                            NOT NULL,
    mpesa_short_code VARCHAR(255),
    currency         VARCHAR(255),
    active           BOOLEAN,
    CONSTRAINT pk_smp_registered_services PRIMARY KEY (id)
);

CREATE TABLE smp_users
(
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at                      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by                      VARCHAR(255),
    updated_by                      VARCHAR(255),
    user_id                         VARCHAR(255),
    email                           VARCHAR(255),
    first_name                      VARCHAR(255),
    middle_name                     VARCHAR(255),
    last_name                       VARCHAR(255),
    password                        VARCHAR(255),
    role                            VARCHAR(255),
    enabled                         BOOLEAN                                 NOT NULL,
    deleted                         BOOLEAN                                 NOT NULL,
    deleted_at                      TIMESTAMP WITHOUT TIME ZONE,
    deleted_by                      VARCHAR(255),
    email_verified                  BOOLEAN,
    email_verification_token        VARCHAR(255),
    email_verification_token_expiry TIMESTAMP WITHOUT TIME ZONE,
    password_reset_token            VARCHAR(255),
    password_reset_token_expiry     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_smp_users PRIMARY KEY (id)
);

ALTER TABLE smp_payment_transactions
    ADD CONSTRAINT uc_smp_payment_transactions_subscriptionid UNIQUE (subscription_id);

ALTER TABLE smp_registered_services
    ADD CONSTRAINT uc_smp_registered_services_apikey UNIQUE (api_key);

ALTER TABLE smp_registered_services
    ADD CONSTRAINT uc_smp_registered_services_name UNIQUE (name);

ALTER TABLE smp_users
    ADD CONSTRAINT uc_smp_users_email UNIQUE (email);

ALTER TABLE smp_users
    ADD CONSTRAINT uc_smp_users_userid UNIQUE (user_id);